% $Author: Peter Gagarinov, PhD <pgagarinov@gmail.com> $
% $Copyright: 2015-2016 Peter Gagarinov, PhD
%             2012-2015 Moscow State University,
%            Faculty of Applied Mathematics and Computer Science,
%            System Analysis Department$
classdef EmailLoggerBuilder
    methods (Access=private)
        function self=EmailLoggerBuilder()
        end
    end
    methods (Static)
        function emailLogger=fromConfRepoMgr(confRepoMgr,appName,...
                inpSubjSuffName,mainLogFileName,fTempDirGetter,varargin)
            %
            import mxberry.core.throwerror;
            [~,~,addAttachNameList]=mxberry.core.parseparext(varargin,...
                {'emailAttachmentNameList';...
                {};...
                'iscellofstring(x)'},0);
            [urlCodeStr,urlStr,branchName,revisionStr]=...
                mxberry.dev.scm.getrepoparams();
            %
            tmpDirName=fTempDirGetter(appName);
            %zip log file name
            zipLogFileName=[tmpDirName,filesep,'mainlog.zip'];
            %
            dstConfFileName=[tmpDirName,filesep,'cur_conf','.xml'];
            confRepoMgr.copyConfFile(dstConfFileName,'destIsFile',true);
            %
            
            [~,pidVal,~]=mxberry.system.getpidhost();
            subjectSuffix=[',pid:',num2str(pidVal),',conf:',...
                confRepoMgr.getCurConfName(),inpSubjSuffName,...
                ',',urlCodeStr,':',urlStr];
            addArgList={};
            if confRepoMgr.isParam('emailNotification.smtpUserName')
                addArgList=[addArgList,{'smtpUserName',...
                    confRepoMgr.getParam('emailNotification.smtpUserName')}];
                if confRepoMgr.isParam('emailNotification.smtpPassword')
                    addArgList=[addArgList,{'smtpPassword',...
                        confRepoMgr.getParam('emailNotification.smtpPassword')}];
                end
            elseif confRepoMgr.isParam('emailNotification.smtpPassword')
                throwerror('wrongInput',['smtpPassword can only be ',...
                    'specified when smtpUser name is specified']);
            end
            %
            if confRepoMgr.isParam('emailNotification.from.isEnabled')
                fromEmailAddress=confRepoMgr.getParam(...
                    'emailNotification.from.emailAddress');
                inpArgList={'fromEmailAddress',fromEmailAddress};
            else
                inpArgList={};
            end
            %
            emailLogger=mxberry.log.EmailLogger(...
                'emailDistributionList',...
                confRepoMgr.getParam('emailNotification.distributionList'),...
                'emailAttachmentNameList',...
                [{mainLogFileName,dstConfFileName},addAttachNameList],...
                'emailAttachmentZippedNameList',...
                [{zipLogFileName},cell(1,numel(addAttachNameList)+1)],...
                'smtpServer',confRepoMgr.getParam('emailNotification.smtpServer'),...
                'subjectSuffix',subjectSuffix,...
                'loggerName',...
                [appName,':',branchName,':',revisionStr],addArgList{:},...
                'dryRun',...
                ~confRepoMgr.getParam('emailNotification.isEnabled'),...
                inpArgList{:});
        end
    end
end